"""
Bare-bones tuning for autonomous + odom + detection only.
Keep this small and explicit while debugging behavior.
"""

# Command mapping
HOST_LINEAR_CMD_SCALE = -1.0
ARM_SHOULDER_CMD = 1400
ARM_CLAW_CMD = 4500

# Startup behavior
START_MODE = "detect"
FIXED_BALL_TRAVEL_FRAMES = 0
FIXED_BUCKET_TRAVEL_FRAMES = 120
FIXED_BACK_TRAVEL_FRAMES = 60
SWIVEL_SMALL_LEFT_FRAMES = 70
SWIVEL_LARGE_RIGHT_FRAMES = 360
MAX_LAPS = 4

# Initial odom objective to get closer to the ball cluster before visual lock.
INITIAL_BALL_ZONE_GOAL_ENABLE = True
INITIAL_BALL_ZONE_FORWARD_M = 3.8
INITIAL_BALL_ZONE_V_MAX = 0.16
INITIAL_BALL_ZONE_W_MAX = 0.30
INITIAL_BALL_ZONE_STOP_DIST_M = 0.45

# Detection
MIN_CONFIDENCE = 0.35
CONFIRM_FRAMES = 3
CLOSE_CONFIRM_FRAMES = 3

KNOWN_COLOR_TOKENS = (
    "blue ball",
    "blue bucket",
    "green ball",
    "green bucket",
    "red ball",
    "red bucket",
    "yellow ball",
    "yellow bucket",
)
TARGET_BALL_COLOR = "red ball"
TARGET_ONLY_ON_FIRST_LAP = True
FALLBACK_TO_ANY_BALL_IF_TARGET_MISSING = True
TARGET_FALLBACK_FRAMES = 45
BUCKET_FALLBACK_TO_ANY_IF_TARGET_MISSING = False
BUCKET_TARGET_FALLBACK_FRAMES = 120

# Geometry/depth
FOCAL_PX = 3386.0
BALL_HEIGHT_M = 0.1524
BUCKET_HEIGHT_M = 0.381
MIN_VALID_DEPTH_M = 0.10
DEPTH_KERNEL_RADIUS = 2

# Ball approach
BALL_FAR_M = 6.0
BALL_MID_M = 1.4
BALL_PICK_MIN_M = 0.56
BALL_PICK_MAX_M = 0.67
BALL_PICK_HARD_STOP_MARGIN_M = 0.04
BALL_NO_DEPTH_NEAR_STOP_M = 0.80
BALL_TOO_CLOSE_BACKUP_LIN = 0.35
BALL_SPEED_FAR = -0.30
BALL_SPEED_MID = -0.18
BALL_SPEED_NEAR = -0.07
BALL_CENTER_TOL_FOR_PICK = 0.08

# Bucket approach
BUCKET_FAR_M = 4.0
BUCKET_MID_M = 1.5
BUCKET_DROP_MIN_M = 0.41
BUCKET_DROP_MAX_M = 0.55
BUCKET_TOO_CLOSE_BACKUP_LIN = 0.30
BUCKET_SPEED_FAR = -0.30
BUCKET_SPEED_MID = -0.14
BUCKET_SPEED_NEAR = -0.08
BUCKET_CENTER_TOL_FOR_DROP = 0.10

# Steering
STEER_KP = 1.6
MAX_TURN_RATE = 0.55
CENTER_DEADBAND = 0.03
MISALIGN_ERR_FOR_SLOWDOWN = 0.16
MISALIGN_LINEAR_SCALE = 0.65

# Search
SEARCH_START_FRAMES = 7
BALL_SEARCH_TURN_RATE = 0.22
BUCKET_SEARCH_TURN_RATE = 0.22
BALL_SEARCH_FORWARD_LIN = -0.10
BUCKET_SEARCH_FORWARD_LIN = -0.10
SEARCH_PHASE_FRAMES = 24
SEARCH_WIDE_TURN_MULT = 1.45
SEARCH_ARC_TURN_MULT = 0.55

# Arm timing
PICK_LOWER_FRAMES = 34
PICK_CLOSE_FRAMES = 85
PICK_RAISE_FRAMES = 60
DROP_LOWER_FRAMES = 24
DROP_OPEN_FRAMES = 34
TURN_TO_CENTER_AFTER_DROP = True

# Odom
ODOM_ENABLE = True
ODOM_CAM_OFFSET_X_M = -0.64
ODOM_CAM_OFFSET_Y_M = 0.0
ODOM_CAM_OFFSET_Z_M = 0.2
ODOM_KP_V = 0.5
ODOM_KP_W = 0.5
ODOM_MAX_V = 0.30
ODOM_MAX_W = 0.60
ODOM_GOAL_TOLERANCE_M = 0.05
ODOM_FORWARD_IS_NEGATIVE = True
ODOM_ASSIST_BALL_ENABLE = True
ODOM_ASSIST_BUCKET_ENABLE = True
ODOM_CMD_EPSILON = 0.01
ODOM_GOAL_UPDATE_MIN_DELTA_M = 0.02
ODOM_GOAL_RESPECT_COLOR_FILTER = True
ODOM_GOAL_DEPTH_KERNEL_RADIUS = 2
ODOM_GOAL_HYSTERESIS_ENABLE = True
ODOM_GOAL_HYSTERESIS_M = 0.06
ODOM_REQUIRE_VISION_SIGN_MATCH = True
ODOM_CLEAR_GOAL_WHEN_BALL_LOST = True
ODOM_CLEAR_GOAL_WHEN_BUCKET_LOST = True
ODOM_RESET_COUNTERS_EACH_LAP = True